apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-test-app
  namespace: k8s-test-app
  labels:
    app: k8s-test-app
spec:
  selector:
    matchLabels:
      app: k8s-test-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
