apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: k8s-test-app
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: zap
          image: ghcr.io/zaproxy/zaproxy:stable
          volumeMounts:
            - name: zap-work
              mountPath: /zap/wrk
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              mkdir -p /zap/wrk/python
              export PIP_TARGET="/zap/wrk/python"
              export PYTHONPATH="/zap/wrk/python:$PYTHONPATH"
              zap-baseline.py -t http://k8s-test-app.k8s-test-app.svc.cluster.local -I -r /zap/wrk/report.html -w /zap/wrk/report.md
              echo "===== BEGIN ZAP REPORT.MD ====="
              cat /zap/wrk/report.md
              echo "===== END ZAP REPORT.MD ====="
      volumes:
        - name: zap-work
          emptyDir: {}
      restartPolicy: Never
